### ISSUE TITLE
receiver: unknown command 'eval' after sending data

### ISSUE THREAD

**Issue by codker** [noahhl/batsd#2]
I'm trying batsd, but whenever I send a stat, after a while it will pop an exception in the console (but data is saved to redis)

``` ruby
Thread #<Thread:0x000000015e0de8> error: ERR unknown command 'eval' ERR unknown command 'eval' /home/luca/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis/client.rb:43:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:1647:in `block in method_missing'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:55:in `block in synchronize'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:49:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:49:in `block (2 levels) in initialize'
~/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:49:in `block in initialize'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:55:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:55:in `synchronize'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0.rc1/lib/redis.rb:1646:in `method_missing'
~/Desktop/batsd/lib/batsd/redis.rb:74:in `get_and_clear_key'
~/Desktop/batsd/lib/batsd/handlers/counter.rb:100:in `block (5 levels) in flush'
~/Desktop/batsd/lib/batsd/handlers/counter.rb:98:in `each'
~/Desktop/batsd/lib/batsd/handlers/counter.rb:98:in `block (4 levels) in flush'
~/Desktop/batsd/lib/batsd/threadpool.rb:17:in `call'
~/Desktop/batsd/lib/batsd/threadpool.rb:17:in `block (3 levels) in initialize'
~/Desktop/batsd/lib/batsd/threadpool.rb:14:in `loop'
~/Desktop/batsd/lib/batsd/threadpool.rb:14:in `block (2 levels) in initialize'
```

if I update redis gem to the latest 3.0.0 stable, it will give me this instead:

``` ruby
Thread #<Thread:0x00000002d8c7d0> error: undefined method `length' for 1:Fixnum undefined method `length' for 1:Fixnum ~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0/lib/redis.rb:2122:in `block in _eval'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0/lib/redis.rb:36:in `block in synchronize'
~/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0/lib/redis.rb:36:in `synchronize'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0/lib/redis.rb:2121:in `_eval'
~/.rvm/gems/ruby-1.9.3-p194/gems/redis-3.0.0/lib/redis.rb:2148:in `eval'
~/Desktop/batsd/lib/batsd/redis.rb:74:in `get_and_clear_key'
~/Desktop/batsd/lib/batsd/handlers/counter.rb:100:in `block (5 levels) in flush'
~/Desktop/batsd/lib/batsd/handlers/counter.rb:98:in `each'
~/Desktop/batsd/lib/batsd/handlers/counter.rb:98:in `block (4 levels) in flush'
~/Desktop/batsd/lib/batsd/threadpool.rb:17:in `call'
~/Desktop/batsd/lib/batsd/threadpool.rb:17:in `block (3 levels) in initialize'
~/Desktop/batsd/lib/batsd/threadpool.rb:14:in `loop'
~/Desktop/batsd/lib/batsd/threadpool.rb:14:in `block (2 levels) in initialize'
```

**Comment by lucaspiller** [comment]
Are you running Redis 2.6? The first errors looks like you are running an old version, as the `eval` command is new in the 2.6 release to run Lua scripts.

**Comment by codker** [comment]
you're right, i'm running the stable version. with 2.6 it's ok :)
